CREATE TABLE `user_video_configs` (
  `id` varchar(36) NOT NULL, `user_id` varchar(36) NOT NULL, `name` varchar(80) NOT NULL,
  `comfy_base_url` varchar(512) NOT NULL, `comfy_token` text, `workflow_dir` varchar(512) NOT NULL,
  `rewrite_enabled` int unsigned NOT NULL DEFAULT 0, `rewrite_base_url` varchar(512), `rewrite_model` varchar(160), `rewrite_api_key` text,
  `default_width` int unsigned NOT NULL DEFAULT 576, `default_height` int unsigned NOT NULL DEFAULT 320, `default_frames` int unsigned NOT NULL DEFAULT 49, `default_fps` int unsigned NOT NULL DEFAULT 8, `default_steps` int unsigned NOT NULL DEFAULT 20,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`), KEY `user_video_configs_user_updated_idx` (`user_id`,`updated_at`), CONSTRAINT `user_video_configs_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade
);--> statement-breakpoint
CREATE TABLE `video_generations` (
  `id` varchar(36) NOT NULL, `request_id` varchar(36) NOT NULL, `request_hash` varchar(64) NOT NULL, `user_id` varchar(36) NOT NULL, `conversation_id` varchar(36) NOT NULL, `user_message_id` varchar(36) NOT NULL, `assistant_message_id` varchar(36), `video_config_id` varchar(36), `video_preset_id` varchar(64) NOT NULL, `mode` enum('text-to-video','image-to-video','text-image-to-video') NOT NULL, `model` varchar(160) NOT NULL DEFAULT 'Wan2.1', `prompt` text NOT NULL, `rewritten_prompt` text, `negative_prompt` text, `shot_plan` text, `reference_attachment_ids` json NOT NULL, `width` int unsigned NOT NULL, `height` int unsigned NOT NULL, `frames` int unsigned NOT NULL, `fps` int unsigned NOT NULL, `steps` int unsigned NOT NULL, `comfy_prompt_id` varchar(128), `workflow_version` varchar(64), `status` enum('queued','running','completed','failed','cancel_requested','cancelled') NOT NULL, `error_code` varchar(64), `started_at` datetime, `completed_at` datetime, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `video_generations_user_request_unique` (`user_id`,`request_id`), KEY `video_generations_queue_idx` (`status`,`created_at`), KEY `video_generations_user_created_idx` (`user_id`,`created_at`), CONSTRAINT `video_generations_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade, CONSTRAINT `video_generations_conversation_fk` FOREIGN KEY (`conversation_id`) REFERENCES `conversations`(`id`) ON DELETE cascade, CONSTRAINT `video_generations_message_fk` FOREIGN KEY (`user_message_id`) REFERENCES `messages`(`id`) ON DELETE cascade, CONSTRAINT `video_generations_config_fk` FOREIGN KEY (`video_config_id`) REFERENCES `user_video_configs`(`id`) ON DELETE SET NULL
);
