import { randomUUID } from "crypto";
import { desc, eq } from "drizzle-orm";
import { getDb } from "@/server/db";
import { userVideoConfigs } from "@/server/db/schema";
import { RequestError } from "@/server/http/errors";
import type { z } from "zod";
import type { videoConfigSchema } from "@/shared/validators";

export type VideoConfigInput = z.infer<typeof videoConfigSchema>;
export type VideoConnection = VideoConfigInput & { id: string };
const normalize = (value: string) => value.replace(/\/$/, "");
export function validateLocalVideoUrl(value: string) { const url = new URL(value); const loopback = ["127.0.0.1", "localhost", "::1"].includes(url.hostname); if (!loopback && url.protocol !== "https:") throw new RequestError("远程 ComfyUI 必须使用 HTTPS。"); return normalize(url.href); }
function publicConfig(row: typeof userVideoConfigs.$inferSelect) { return { id: row.id, name: row.name, comfyBaseUrl: row.comfyBaseUrl, workflowDir: row.workflowDir, rewriteEnabled: Boolean(row.rewriteEnabled), rewriteBaseUrl: row.rewriteBaseUrl ?? "", rewriteModel: row.rewriteModel ?? "", comfyTokenConfigured: Boolean(row.comfyToken), rewriteApiKeyConfigured: Boolean(row.rewriteApiKey), defaultWidth: row.defaultWidth, defaultHeight: row.defaultHeight, defaultFrames: row.defaultFrames, defaultFps: row.defaultFps, defaultSteps: row.defaultSteps }; }
export async function getVideoConfig(userId: string) { const row = (await getDb().select().from(userVideoConfigs).where(eq(userVideoConfigs.userId, userId)).orderBy(desc(userVideoConfigs.updatedAt)).limit(1))[0]; return row ? publicConfig(row) : null; }
export async function resolveVideoConfig(userId: string): Promise<VideoConnection> { const row = (await getDb().select().from(userVideoConfigs).where(eq(userVideoConfigs.userId, userId)).orderBy(desc(userVideoConfigs.updatedAt)).limit(1))[0]; if (!row) { const comfyBaseUrl = process.env.COMFYUI_BASE_URL; if (!comfyBaseUrl) throw new RequestError("请先配置视频服务。", 404); return { id: "env-video-config", name: "环境变量视频配置", comfyBaseUrl: validateLocalVideoUrl(comfyBaseUrl), comfyToken: process.env.COMFYUI_API_TOKEN || undefined, workflowDir: process.env.COMFYUI_WORKFLOW_DIR || "./data/comfyui-workflows", rewriteEnabled: process.env.VIDEO_PROMPT_REWRITE_ENABLED === "true", rewriteBaseUrl: process.env.VIDEO_PROMPT_REWRITE_BASE_URL, rewriteModel: process.env.VIDEO_PROMPT_REWRITE_MODEL, rewriteApiKey: process.env.VIDEO_PROMPT_REWRITE_API_KEY, defaultWidth: 576, defaultHeight: 320, defaultFrames: 49, defaultFps: 8, defaultSteps: 20 }; } return { id: row.id, name: row.name, comfyBaseUrl: row.comfyBaseUrl, comfyToken: row.comfyToken ?? undefined, workflowDir: row.workflowDir, rewriteEnabled: Boolean(row.rewriteEnabled), rewriteBaseUrl: row.rewriteBaseUrl ?? undefined, rewriteModel: row.rewriteModel ?? undefined, rewriteApiKey: row.rewriteApiKey ?? undefined, defaultWidth: row.defaultWidth, defaultHeight: row.defaultHeight, defaultFrames: row.defaultFrames, defaultFps: row.defaultFps, defaultSteps: row.defaultSteps }; }
export async function saveVideoConfig(userId: string, input: VideoConfigInput) { const existing = (await getDb().select().from(userVideoConfigs).where(eq(userVideoConfigs.userId, userId)).orderBy(desc(userVideoConfigs.updatedAt)).limit(1))[0]; const values = { name: input.name, comfyBaseUrl: validateLocalVideoUrl(input.comfyBaseUrl), comfyToken: input.comfyToken || existing?.comfyToken || null, workflowDir: input.workflowDir, rewriteEnabled: input.rewriteEnabled ? 1 : 0, rewriteBaseUrl: input.rewriteBaseUrl ? validateLocalVideoUrl(input.rewriteBaseUrl) : null, rewriteModel: input.rewriteModel || null, rewriteApiKey: input.rewriteApiKey || existing?.rewriteApiKey || null, defaultWidth: input.defaultWidth, defaultHeight: input.defaultHeight, defaultFrames: input.defaultFrames, defaultFps: input.defaultFps, defaultSteps: input.defaultSteps }; if (existing) await getDb().update(userVideoConfigs).set(values).where(eq(userVideoConfigs.id, existing.id)); else await getDb().insert(userVideoConfigs).values({ id: randomUUID(), userId, ...values }); return getVideoConfig(userId); }
export async function deleteVideoConfig(userId: string) { await getDb().delete(userVideoConfigs).where(eq(userVideoConfigs.userId, userId)); }
